### ISSUE TITLE
Get everything if no query provided

### ISSUE THREAD

**Issue by kkharji** [RishabhRD/nvim-cheat.sh#7]
Great implementation @RishabhRD

**Comment by RishabhRD** [comment]
hi @tami5 , Great idea. Using ``curl cht.sh/:list``, we can get the list of
commands.

There are many ways for implementing it. One is just to show the list in
the result window. Another idea can be to show a fuzzy finding interface for every
symbol in the list.  Both things are trivial using popfix and should not result in
a massive increase in code.

What you think, which one would be better? Because I am feeling fuzzy finding
interface for symbols can have more use-cases. For example, users can choose
one of the symbols from the list that can be the initial text for a new prompt.

**Comment by kkharji** [comment]
@RishabhRD Oh that's even better 😍, perhaps we can use both by having an `all` item and if the user select it then the window should show all of them

**Comment by RishabhRD** [comment]
Yeah great. Then I would make a PR in a few hours and I would also mention you in
the comment for notification.  You can help me with the implementation of the feature.
So that we don't miss any point in implementation. :smile:

**Comment by kkharji** [comment]
Sure thing @RishabhRD looking forward
